[global]
   workgroup = NOVATECH
   server string = NovaCorp File Server
   security = user
   map to guest = Never
   log file = /var/log/samba/%m.log
   max log size = 50

[share]
   path = /srv/share
   browseable = yes
   read only = yes
   valid users = smbuser
   comment = NovaCorp Internal Documents
