options {
    directory "/var/bind";
    listen-on { any; };
    allow-query { any; };
    # MISCONFIGURATION: zone transfers allowed from anyone
    allow-transfer { any; };
    recursion no;
};

zone "novatech.local" {
    type master;
    file "/var/bind/novatech.local.zone";
};
