#!/bin/bash
echo ""
echo "==========================================="
echo "  CAPEC-309: Network Topology Mapping Lab"
echo "  IT&C 266 — Attack Pattern Repository"
echo "==========================================="
echo ""
echo "  Your IP:    10.10.10.50"
echo "  Known net:  10.10.10.0/24 (DMZ)"
echo ""
echo "  Objective: Map the full network topology."
echo "  Find all hosts, services, and 5 flags."
echo ""
echo "  Tools available: nmap, dig, traceroute,"
echo "  ncat, curl, smbclient"
echo ""
echo "  Type 'nmap -h' to get started."
echo "==========================================="
echo ""
